<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rsp</string>
		<string>html.rsp</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>injections</key>
	<dict>
		<key>L:(text.html.rsp - (meta.embedded.block.rsp | comment.block.rsp))</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tags</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>keyEquivalent</key>
	<string>^~H</string>
	<key>name</key>
	<string>HTML (Rebol - RSP)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;%#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.rsp</string>
						</dict>
					</dict>
					<key>end</key>
					<string>%&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.rsp</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.rsp</string>
				</dict>
			</array>
		</dict>
		<key>tags</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;%(==|=|!)?(?=\s)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.rsp</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.rebol</string>
					<key>end</key>
					<string>(-?%)&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.rsp</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.rebol</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.rsp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.rebol</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.rsp</string>
	<key>uuid</key>
	<string>EC777AAA-5802-4640-AFF9-3BC95CCECEE7</string>
</dict>
</plist>
