<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>feed.rsp</string>
		<string>xml.rsp</string>
		<string>svg.rsp</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>injections</key>
	<dict>
		<key>L:(text.xml.rsp - (meta.embedded.block.rsp | comment.block.rsp))</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tags</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>name</key>
	<string>XML (Rebol - RSP)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.xml</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;%#</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.begin.rsp</string>
						</dict>
					</dict>
					<key>end</key>
					<string>%&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.end.rsp</string>
						</dict>
					</dict>
					<key>name</key>
					<string>comment.block.rsp</string>
				</dict>
			</array>
		</dict>
		<key>tags</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;(%(==|=|!)?)(?=\s)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.begin.rsp</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>source.rebol</string>
					<key>end</key>
					<string>(%)&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.end.rsp</string>
						</dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>source.rebol</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.embedded.block.rsp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.rsp</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(#).*?(?=-?%&gt;)</string>
							<key>name</key>
							<string>comment.line.number-sign.rsp</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.rebol</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.xml.rsp</string>
	<key>uuid</key>
	<string>4A8301AB-40B9-4513-A90F-457FDE234221</string>
</dict>
</plist>
